import UsmanGanichareman from '../../assets/UsmanGanichareman.jpg';

export const teamMembers = [
  {
    name: "Usman Gani",
    role: "Founder & CEO",
    image: UsmanGanichareman,
    // email: "PH : 0321-1234567",
    about: "Founder & visionary leader, turning bold ideas into impactful realities with innovation and strategy.",
    isOwner: true,
    type: "team", 
  },
  {
    name: "Rana Muhammad Mushtaq khan",
    role: "Joint Sectory",
    image: "./src/assets/Rana Muhammad Mushtaq khan  joint sectory.jpg",
    // email: "0300-1234567",
    about: "Dedicated to fostering collaboration and driving success through strategic partnerships.",
    isOwner: false,
    type: "team",
  }, 
  {
    name: "Muhammad Shabaz",
    role: "Voice Chariman",
    image: "./src/assets/Shabaz.jpg",
    // email: "0300-1234567",
    about: "Dedicated to fostering collaboration and driving success through strategic partnerships.",
    isOwner: false,
    type: "team",
  },
  {
    name: "Muhammad Qasim",
    role: "Information Sectory",
    image: "./src/assets/Muhammad Qasim  information sectory.jpg",
    // email: "0300-1234567",
    about: "Ensuring smooth communication across the team and managing information flow with clarity and precision.",
    isOwner: false,
    type: "team",
  },
  {
    name: "Rana Mubashir Ali khan",
    role: "Office Sectory",
    image: "./src/assets/Rana_Mubashir_Ali_khan__Office_sectrory-removebg-preview.png",
    // email: "0300-1234567",
    about: "Overseeing office operations and ensuring a productive work environment.",
    isOwner: false,
    type: "team",
  },
  {
    name: "Shumaila Sadaiq",
    role: "Finance Sectory",
    image: "./src/assets/lad-removebg-preview.png",
    // email: "0300-1234567",
    about: "Managing financial resources and ensuring fiscal responsibility.",
    isOwner: false,
    type: "team",
  },
  {
    name: "Rao Naveed Imran",
    role: "Joint Sectory",
    image: "./src/assets/Rao Naveed imran joint sectory (1).jpg",
    // email: "0300-1234567",
    about: "Dedicated to fostering collaboration and driving success through strategic partnerships.",
    isOwner: false,
    type: "team",
  },
   {
    name: "Chudhary Usman Shabeer",
    role: "Genral Sectory",
    image: "./src/assets/chudhary usman Shabeer  Genral sectory.png",
    // email: "0300-1234567",
    about: "Ensuring smooth communication across the team and managing information flow with clarity and precision.",
    isOwner: false,
    type: "team",
  }
 
];

export const volunteers = [
  {
    name: "Abid ali khan",
    role: "Volunteer Designer",
    image: "./src/assets/volenter/Abid ali khan v .jpg",
    // email: "0321-1234567",
    about: "Passionate volunteer dedicated to making a positive impact through creative design and teamwork.",
    type: "volunteer",
  },
  {
    name: "Awais Manj",
    role: "Volunteer Designer",
    image: "./src/assets/volenter/Awais manj v .jpg",
    // email: "0321-1234567",
    about: "Passionate volunteer dedicated to making a positive impact through creative design and teamwork.",
    type: "volunteer",
  },
  {
    name: "Hafiz Shuja sahbaz",
    role: "Volunteer Designer",
    image: "./src/assets/volenter/Hafiz Shuja sahbaz v.jpg",
    // email: "0321-1234567",
    about: "Passionate volunteer dedicated to making a positive impact through creative design and teamwork.",
    type: "volunteer",
  },
  {
    name: "Imran Shaheen",
    role: "Volunteer Designer",
    image: "./src/assets/volenter/Imran shaheen v .jpg",
    // email: "0321-1234567",
    about: "Passionate volunteer dedicated to making a positive impact through creative design and teamwork.",
    type: "volunteer",
  },
  {
    name: "Rana Sulaman Mumtaz",
    role: "Volunteer Designer",
    image: "./src/assets/volenter/Rana Sulaman Mumtaz v.jpg",
    // email: "0333-1234567",
    about: "Committed to supporting the team with innovative design solutions and a collaborative spirit.",
    type: "volunteer",
  },
  {
    name: "Rana Usman Islam",
    role: "Volunteer Designer",
    image: "./src/assets/volenter/Rana Usman  Islam v.jpg",
    // email: "0321-1234567",
    about: "Passionate volunteer dedicated to making a positive impact through creative design and teamwork.",
    type: "volunteer",
  }
];
